# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

# format = """
# 
# $character
# """
format = """
$cmd_duration$directory$python$git_branch$git_status
$character
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[• ](bold fg:green) "
error_symbol = "[• 󰅙](bold fg:red) "

[cmd_duration]
min_time = 0
format = '[](bold fg:yellow)[ $duration](bold bg:yellow fg:black)[](bold fg:yellow) •• '

[hostname]
ssh_only = false
format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan ) • "
trim_at = ".companyname.com"
disabled = false

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:green fg:black"
truncation_length = 6
truncation_symbol = "••/"
format = '[](bold fg:green)[$path ]($style)[](bold fg:green)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "

[python]
style = "bg: green"
format = ' • [](bold fg:green)[$version \($virtualenv\)](fg:black bg:green)[](bold fg:green)'

[git_branch]
style = "bg: green"
symbol = "󰘬"
truncation_length = 7
truncation_symbol = ""
format = " • [](bold fg:green)[$symbol $branch(:$remote_branch)](fg:black bg:green)"

[git_status]
format = "[$ahead_behind](fg:black bg:green)[](bold fg:green)"
ahead = " ↑$count"
behind = " ↓$count"
diverged = " ↑$ahead_count ↓$behind_count"
